name: "ccmatrix_en-it"
joeynmt_version: "2.1.0"

data:
    train: "./ccmatrix_en-it/train"
    dev: "./ccmatrix_en-it/validation"
    test: "./ccmatrix_en-it/test"
    dataset_type: "huggingface"
    sample_dev_subset: 200
    src:
        lang: "en"
        max_length: 100
        lowercase: False
        normalize: False
        level: "bpe"
        voc_limit: 32000
        voc_min_freq: 1
        voc_file: "./ccmatrix_en-it/vocab.txt"
        tokenizer_type: "sentencepiece"
        tokenizer_cfg:
            model_file: "./ccmatrix_en-it/sp.model"

    trg:
        lang: "it"
        max_length: 100
        lowercase: False
        normalize: False
        level: "bpe"
        voc_limit: 32000
        voc_min_freq: 1
        voc_file: "./ccmatrix_en-it/vocab.txt"
        tokenizer_type: "sentencepiece"
        tokenizer_cfg:
            model_file: "./ccmatrix_en-it/sp.model"

testing:
    n_best: 1
    beam_size: 5
    beam_alpha: 1.0
    batch_size: 64
    batch_type: "token"
    eval_metrics: ["bleu"]

training:
    random_seed: 123
    optimizer: "adam"
    normalization: "tokens"
    scheduling: "plateau"
    learning_rate: 0.001
    weight_decay: 0.0
    batch_size: 128
    batch_type: "token"
    early_stopping_metric: "bleu"
    epochs: 20
    validation_freq: 2000
    logging_freq: 100
    model_dir: "./lstm_model_small"
    overwrite: True
    shuffle: True
    use_cuda: True
    fp16: False
    print_valid_sents: [0, 1, 2]
    keep_best_ckpts: 3

model:
    initializer: "xavier_uniform"
    bias_initializer: "zeros"
    embed_initializer: "xavier_uniform"
    encoder:
        type: "recurrent"
        rnn_type: "lstm"
        num_layers: 1
        bidirectional: True
        embeddings:
            embedding_dim: 300
        hidden_size: 128
    decoder:
        type: "recurrent"
        rnn_type: "lstm"
        num_layers: 1
        embeddings:
            embedding_dim: 300
        hidden_size: 128

